import numpy as np
import cv2

class DensityEstimator:
    def __init__(self, width, height, grids, default_sigma=15.0):
        """
        Initializes the density estimator.
        width, height: dimensions of the frame.
        grids: list of grid dictionaries generated by GridGenerator.
        default_sigma: standard deviation for the Gaussian kernel.
        """
        self.width = width
        self.height = height
        self.grids = grids
        self.default_sigma = default_sigma

        # Precompute the overlap weights (Method B - Weight Normalization)
        self.grid_count_map = np.zeros((height, width), dtype=np.float32)
        for g in grids:
            self.grid_count_map[g["y1"]:g["y2"], g["x1"]:g["x2"]] += 1.0

        # Avoid division by zero
        self.grid_weight_map = 1.0 / np.maximum(self.grid_count_map, 1.0)

    def generate_density_map(self, points, sigma=None):
        """
        Generates a density map from a list of point annotations.
        points: list of dicts with {"x": px, "y": py}
        sigma: standard deviation of the Gaussian kernel.
        """
        if sigma is None:
            sigma = self.default_sigma

        density_map = np.zeros((self.height, self.width), dtype=np.float32)

        # Kernel radius
        r = int(4 * sigma)

        for pt in points:
            x, y = int(pt["x"]), int(pt["y"])
            if x < 0 or x >= self.width or y < 0 or y >= self.height:
                continue

            # Define localized bounding box for the Gaussian kernel
            x1 = max(0, x - r)
            y1 = max(0, y - r)
            x2 = min(self.width, x + r + 1)
            y2 = min(self.height, y + r + 1)

            # Generate local coordinates centered on the point
            xx, yy = np.meshgrid(np.arange(x1, x2), np.arange(y1, y2))
            dist_sq = (xx - x)**2 + (yy - y)**2

            # Gaussian formula
            kernel = np.exp(-dist_sq / (2.0 * sigma**2))
            kernel /= (2.0 * np.pi * sigma**2)

            # Add to density map
            density_map[y1:y2, x1:x2] += kernel

        return density_map

    def map_density_to_grids(self, density_map):
        """
        Computes the weighted count and density for each grid.
        Returns a dictionary mapping grid_id to (count, density).
        """
        grid_metrics = {}
        for g in self.grids:
            x1, y1, x2, y2 = g["x1"], g["y1"], g["x2"], g["y2"]
            area = g["area"]

            # Extract local density and weight
            local_density = density_map[y1:y2, x1:x2]
            local_weight = self.grid_weight_map[y1:y2, x1:x2]

            # Compute weighted count
            weighted_count = np.sum(local_density * local_weight)

            # Compute unweighted count (for local density reporting)
            local_count = np.sum(local_density)

            # Density in people per unit area
            # We use local_count for local density representation, but weighted_count for total global summation
            grid_density_score = local_count / area if area > 0 else 0

            grid_metrics[g["grid_id"]] = {
                "weighted_count": float(weighted_count),
                "local_count": float(local_count),
                "density_score": float(grid_density_score)
            }

        return grid_metrics
